### ISSUE TITLE
OAuth2: client credentials flow

### ISSUE THREAD

**Issue by ic-hv** [europace/kex-vorgang-export-api#21]
Beim Export von Vorgängen unter Verwendung des "client credentials flow" wird der Request mit `"statusMessage":"Unauthorized"` quittiert. Der API-Client wurde im Partner-Management entsprechend konfiguriert:

![Bildschirmfoto 2020-08-03 um 15 18 49](https://user-images.githubusercontent.com/26538616/89186882-b9615680-d59c-11ea-9e5c-6bf4f90c1107.png)

P.S: Der "resource owner password credentials" - Flow funktioniert problemlos.

**Comment by smrosek** [comment]
Hi, 
für mich sieht dem Screenshot nach so aus, als wenn verwendete Schnittstelle und Client Credentials nicht zusammen passen. Für die Angebote ermitteln Schnittstelle braucht der Client das Recht "Kreditsmartangebote ermitteln". Im Screenshot ist "Kreditsmartvorgänge lesen" gesetzt, damit können Vorgangsdaten gelesen werden. Melde Dich bitte wieder, wenn das nicht weiter geholfen hat. Danke!
Grüße
Sebastian

**Comment by ic-hv** [comment]
Sorry, ich meinte natürlich Vorgänge exportieren ...

**Comment by smrosek** [comment]
Die weitere Analyse möchte ich gerne in unserem Support Tool weiter führen, um hier keine personenbezogenen Daten zu posten. Kannst Du Dich bitte mit einem Verweis auf dieses Issue an kredit.helpdesk@europace2.de wenden. Ich melde mich dann bei Dir.
Vielen Dank.

**Comment by ic-hv** [comment]
Hat sich erledigt - Problem war: Ich hatte das "client credential" Token noch mittels 'X-Authentication' - Header eingebunden. Sobald man dafür den Header "Authorization: Bearer" verwendet, klappts!
